# Generated by Django 3.2.7 on 2021-10-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Created', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('user_question', models.CharField(blank=True, default='', max_length=100)),
                ('support_answer', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='In progress', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_problems', to=settings.AUTH_USER_MODEL)),
                ('title_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='useractions.problem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
