# Generated by Django 3.2.7 on 2021-10-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdetail',
            name='title_number',
        ),
    ]
