# Generated by Django 3.2.7 on 2021-10-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0005_alter_problemdetail_title_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdetail',
            name='title_number',
        ),
    ]
