# Generated by Django 3.2.7 on 2021-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0006_remove_problemdetail_title_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdetail',
            name='title_id',
            field=models.IntegerField(default=1),
        ),
    ]
