# Generated by Django 3.2.7 on 2021-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0008_auto_20211004_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdetail',
            name='status',
            field=models.CharField(default='In progress', max_length=100),
        ),
    ]
