# Generated by Django 3.2.7 on 2021-10-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0009_alter_problemdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_problem', to='useractions.problem'),
        ),
    ]
