# Generated by Django 3.2.7 on 2021-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0010_alter_problemdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='problemdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
